model:
  type: resnet34
dataset: cifar10
aug: 'default'   # autoaug_extend
cutout: 0
batch: 64
batch_unsup: 64
ratio_unsup: 0.9
ratio_mode: 'constant'
epoch: 1
lr: 0.001
lr_schedule:
  type: 'cosine'
  warmup:
    multiplier: 300
    epoch: 120
optimizer:
  type: sgd
  nesterov: True
  decay: 0.0005

random_state: 0
train_labels: '../results/cifar10/resnet/coresinstance0.6train_noisy_labels.npy'
unsup_idx: '../results/cifar10/resnet/coresinstance0.6_noise_pred.npy'
pretrain: ''

tqdm_disable: False
num_workers: 0